M48
; DRILL file {KiCad 8.0.3-8.0.3-0~ubuntu24.04.1} date 2024-07-12T17:05:28+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-07-12T17:05:28+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3-8.0.3-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X2.4362Y-2.776
X2.6638Y-2.776
M30
