M48
; DRILL file {KiCad 8.0.3-8.0.3-0~ubuntu24.04.1} date 2024-07-13T12:59:11+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-07-13T12:59:11+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3-8.0.3-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X61.88Y-70.51
X67.66Y-70.51
M30
