M48
; DRILL file {KiCad 8.0.4-8.0.4-0~ubuntu24.04.1} date 2024-08-29T15:41:42+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-08-29T15:41:42+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4-8.0.4-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X61.88Y-70.51
X67.66Y-70.51
M30
